/* The AI Counterfactual: case library.
   Every case is SYNTHETIC: constructed to test the method, calibrated to public ranges where a public source exists,
   and never a claim that a real company experienced the modelled result. Names are generic by design. */
(function (global) {
  "use strict";
  function seeded(seed) { var s = (seed >>> 0) || 7; return function () { s ^= s << 13; s >>>= 0; s ^= s >>> 17; s ^= s << 5; s >>>= 0; return s / 4294967296; }; }
  function series(seed, n, base, trend, noise) { var r = seeded(seed), out = []; for (var i = 0; i < n; i++) out.push(+(base + trend * i + (r() - 0.5) * 2 * noise).toFixed(3)); return out; }
  function units(seed, n, mean, sd) { var r = seeded(seed), out = []; for (var i = 0; i < n; i++) { var u = 1 - r(), v = r(); out.push(+(mean + sd * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v)).toFixed(3)); } return out; }

  /* shared public sources used for calibration (from the proposal's source list, accessed 12 September 2026) */
  var PUB = {
    census: { id: "S-CENSUS", grade: "B", type: "Public statistic", cite: "United States Census Bureau, Large Firms With at Least 20 Employees Biggest AI Users, 26 May 2026", url: "https://www.census.gov/library/stories/2026/05/ai-use-businesses.html", excerpt: "17 to 20 percent of United States businesses used AI in at least one function, December 2025 to May 2026." },
    jcurve: { id: "S-JCURVE", grade: "B", type: "Working paper", cite: "McElheran, Yang, Kroff and Brynjolfsson, The Rise of Industrial AI in America: Microfoundations of the Productivity J Curves, Census CES-WP-25-27, April 2025", url: "https://www.census.gov/library/working-papers/2025/adrm/CES-WP-25-27.html", excerpt: "Adjustment costs can harm productivity and profitability in the short run, while earlier adopters show stronger growth over time." },
    genai: { id: "S-GENAI", grade: "A", type: "Published field study", cite: "Brynjolfsson, Li and Raymond, Generative AI at Work, NBER Working Paper 31161", url: "https://www.nber.org/papers/w31161", excerpt: "Access to a generative AI assistant increased productivity, measured by issues resolved per hour, by about 14 percent on average, with the largest gains for less experienced workers." },
    jagged: { id: "S-JAGGED", grade: "A", type: "Published field experiment", cite: "Dell'Acqua and coauthors, Navigating the Jagged Technological Frontier, SSRN 4573321", url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4573321", excerpt: "Consultants using AI completed tasks faster and with higher rated quality inside the frontier, and were more likely to be wrong on a task outside it." },
    ftc: { id: "S-FTC", grade: "B", type: "Regulatory notice", cite: "Federal Trade Commission, FTC Seeks Public Comment on Policy Statement Addressing AI Accuracy, 1 July 2026", url: "https://www.ftc.gov/news-events/news/press-releases/2026/07/ftc-seeks-public-comment-policy-statement-addressing-ai-accuracy", excerpt: "Comment sought on allegedly deceptive representations about AI objectivity, accuracy, effectiveness and suitability." },
    sec: { id: "S-SEC", grade: "B", type: "Regulatory statement", cite: "United States Securities and Exchange Commission, Artificial Intelligence and the Future of Investment Management, 3 February 2026", url: "https://www.sec.gov/newsroom/speeches-statements/daly-020326-artificial-intelligence-future-investment-management", excerpt: "Potential liability when AI produces losses is slowing adoption in investment management." },
    ftcdoj: { id: "S-FTCDOJ", grade: "B", type: "Regulatory notice", cite: "Federal Trade Commission and Department of Justice, Request for Comment on Guidance for Business Collaborations, 23 February 2026", url: "https://www.ftc.gov/news-events/news/press-releases/2026/02/federal-trade-commission-department-justice-seek-public-comment-guidance-business-collaborations", excerpt: "Algorithmic pricing and data sharing identified as subjects for updated competition guidance." }
  };
  function syn(id, excerpt, grade, what) { return { id: id, grade: grade || "D", type: "Synthetic record", cite: what || "Synthetic operating record, generated for this case", excerpt: excerpt, synthetic: true, location: "case packet " + id, date: "2026-09", access: "public", verified: "constructed" }; }
  function pub(p, loc) { return Object.assign({}, p, { location: loc || "as cited", date: "2026-09-12", access: "public", verified: "checked against source" }); }

  var CASES = [

  /* ------------------------------------------------------------------ 1 */
  { id: "KW-01", industry: "Professional services and operations", appClass: "Generation and synthesis", level: "Workflow",
    title: "Generative AI assistant in a customer support operation",
    question: "How much operating profit did a generative AI assistant add to a 480-agent support operation over three years, net of licences, review and the risk of wrong answers, compared with the same operation without it?",
    intendedUse: "Commercial dispute over a vendor's productivity representation; also a valuation input for a services business.",
    unit: "Workflow: issues resolved per agent hour across 24 support teams", unitRationale: "Treatment and outcome are both observed at the team level; firm value follows only through modelled capacity redeployment.",
    period: "2025-Q1 to 2026-Q2", geography: "United States", status: "Reviewed", synthetic: true,
    calibration: "Effect size calibrated to the published field study of a generative AI assistant in customer support (about 14 percent, larger for novices). Volumes, prices and costs are synthetic.",
    treatment: { system: "Retrieval-augmented conversational assistant suggesting replies", version: "v2.3 (model refresh 2025-11 recorded as a new treatment)", deployed: "2025-07-01", scope: "12 of 24 teams first, remaining 12 in 2026-01", autonomy: "Advisory: agents accept, edit or discard suggestions", data: "Historical tickets and knowledge base", users: "480 agents", complements: ["Two-hour training per agent", "Knowledge base cleanup (one-off)", "No change to staffing before month nine"] },
    comparator: { rank: 2, label: "Concurrent phased-rollout control (teams awaiting deployment)", basis: "The 12 later teams handled the same ticket mix under the same management during the first six months.", contamination: ["Cross-team ticket routing checked: under 3 percent of tickets moved between waves", "No concurrent tooling change in either wave"] },
    timeline: [["2025-03-01", "Vendor pilot proposal states 35 percent productivity gain", "claim"], ["2025-06-15", "Knowledge base cleanup completed", "complement"], ["2025-07-01", "Wave one live on 12 teams", "deployment"], ["2025-11-10", "Model refresh v2.3", "version"], ["2026-01-05", "Wave two live", "deployment"], ["2026-03-01", "Headcount plan reduced by 40 through attrition", "economic"]],
    technical: { outcome: "Issues resolved per agent hour", unit: "resolutions per hour", baseline: 2.05 },
    identification: { method: "did", grade: "B", data: { treated: { pre: [2.04, 2.06, 2.05, 2.07, 2.03, 2.06], post: [2.21, 2.30, 2.34, 2.36, 2.37, 2.35] }, control: { pre: [2.02, 2.05, 2.03, 2.06, 2.04, 2.05], post: [2.05, 2.07, 2.06, 2.08, 2.06, 2.07] } },
      assumptions: ["Parallel trends between waves absent treatment (pre-period slopes differ by under 0.01 per month)", "No anticipation by wave-two teams", "Ticket difficulty mix stable across waves"],
      threats: ["Novelty effect in the first two months (addressed: the post window excludes month one)", "Quality drift: resolutions counted only if not reopened within 14 days", "Wave two anticipated deployment and slowed (checked: no pre-period dip)"],
      preTrends: "Pre-period slopes 0.001 (treated) and 0.004 (control) resolutions per hour per month; gap within noise." },
    evidence: [pub(PUB.genai, "Abstract and Table 2"), syn("E-KW-1", "Monthly resolutions per agent hour by team, 12 pre and 6 post months, synthetic", "D", "Synthetic ticket-system export calibrated to the published study"),
               syn("E-KW-2", "Licence schedule: $28 per agent per month, 36-month term", "D", "Synthetic vendor contract"), syn("E-KW-3", "Implementation invoice and internal time: $540,000", "D", "Synthetic project ledger"),
               syn("E-KW-4", "Reopened-ticket rate 4.1 percent with assistant versus 3.6 percent without; average remediation credit $22", "C", "Synthetic quality audit of 2,000 tickets"),
               syn("E-KW-5", "Vendor deck: 35 percent productivity improvement", "E", "Vendor marketing material"), syn("E-KW-6", "Attrition-based headcount reduction plan of 40 agents from month nine", "D", "Synthetic workforce plan"),
               syn("E-KW-7", "Fully loaded cost per agent hour $31", "D", "Synthetic payroll summary")],
    variables: [
      { id: "agents", name: "Agents in scope", value: 480, unit: "agents", evidence: ["E-KW-6"], inference: "Headcount at deployment" },
      { id: "hours", name: "Productive hours per agent per year", value: 1650, unit: "hours", evidence: ["E-KW-7"], inference: "Scheduled hours less leave and training", low: 1550, high: 1720 },
      { id: "baseRate", name: "Resolutions per hour without AI", value: 2.05, unit: "per hour", evidence: ["E-KW-1"], inference: "Control-wave mean" },
      { id: "costPerHour", name: "Loaded cost per agent hour", value: 31, unit: "$", evidence: ["E-KW-7"], inference: "Payroll plus overhead", low: 28, high: 34 },
      { id: "redeploy", name: "Share of time saved that becomes avoided cost", value: 0.55, unit: "share", evidence: ["E-KW-6"], inference: "Only the attrition plan converts capacity into cash; the rest is idle or quality time", low: 0.3, high: 0.8, adverse: "low" },
      { id: "licence", name: "Licence cost per agent per year", value: 336, unit: "$", evidence: ["E-KW-2"], inference: "$28 monthly times 12", low: 300, high: 400, adverse: "high" },
      { id: "implementation", name: "One-off implementation and training", value: 540000, unit: "$", evidence: ["E-KW-3"], inference: "Invoice plus internal time at loaded cost", low: 450000, high: 700000, adverse: "high" },
      { id: "reopenDelta", name: "Extra reopened-ticket rate with AI", value: 0.005, unit: "share of tickets", evidence: ["E-KW-4"], inference: "4.1 minus 3.6 percent", low: 0.0, high: 0.012, adverse: "high" },
      { id: "creditPerReopen", name: "Cost per reopened ticket (credit and rework)", value: 22, unit: "$", evidence: ["E-KW-4"], inference: "Average remediation credit plus 20 minutes rework" },
      { id: "claimedGain", name: "Vendor-claimed productivity gain", value: 0.35, unit: "share", evidence: ["E-KW-5"], inference: "Marketing claim, grade E; used only for the claim-to-value view" },
      { id: "baseProfitYear", name: "Operating profit of the support unit without AI", value: 9200000, unit: "$", evidence: ["E-KW-7"], inference: "Synthetic budget line" }
    ],
    model: { horizonYears: 3, discountRate: 0.10, headStartYears: 3, rampYears: 1,
      channels: { revenue: "0", variableCost: "-(effect * agents * hours / (baseRate + effect)) * costPerHour * redeploy", fixedCost: "agents * licence", capital: "implementation",
                  expectedLoss: "reopenDelta * (baseRate + effect) * agents * hours * creditPerReopen", baseProfit: "baseProfitYear" },
      note: "Time saved is converted to hours at the new rate: hours no longer needed = effect × agents × hours ÷ (base + effect). Only the redeployed share becomes cash.",
      claimedValue: "claimedGain * agents * hours * costPerHour * 3", contributionDenominator: "baseProfitYear * 3",
      welfare: [{ label: "Customer wait time", formula: "-(effect / (baseRate + effect)) * 100", who: "customers", note: "Percent change in average handling time, a nonprice benefit not counted in profit" },
                { label: "Worker task change", formula: "0", who: "workers", note: "No wage change observed in the period; headcount fell through attrition, recorded as a distributional effect not a cash flow" }] },
    alternatives: [
      { id: "prepost", label: "Same teams before and after, no control", rank: 3, method: "did", data: { treated: { pre: [2.04, 2.06, 2.05, 2.07, 2.03, 2.06], post: [2.21, 2.30, 2.34, 2.36, 2.37, 2.35] }, control: { pre: [1, 1, 1, 1, 1, 1], post: [1, 1, 1, 1, 1, 1] } }, note: "Attributes the control group's own 0.02 drift to AI" },
      { id: "novice", label: "Novice agents only (largest published gains)", rank: 2, method: "did", data: { treated: { pre: [1.62, 1.65, 1.64, 1.66, 1.63, 1.65], post: [1.98, 2.10, 2.15, 2.17, 2.18, 2.16] }, control: { pre: [1.61, 1.64, 1.63, 1.65, 1.62, 1.64], post: [1.66, 1.68, 1.67, 1.69, 1.67, 1.68] } }, note: "Not the population effect; shown because the vendor's claim cites it" }
    ],
    assumptionWorlds: [{ label: "Model refresh v2.3 treated as a separate treatment (pre-refresh months only)", overrides: { effect: 0.24 }, note: "The first four post months average a smaller effect; the refresh is a new treatment under the case rules" },
                       { label: "No capacity redeployment (redeploy = 0)", overrides: { redeploy: 0 }, note: "Time saved with no cash consequence: the value is licences and losses only" }],
    distribution: { subgroups: [{ label: "Novice agents (under 6 months)", effect: 0.48 }, { label: "Mid-tenure", effect: 0.29 }, { label: "Senior agents", effect: 0.06 }], note: "Gains concentrate in novices; senior agents see little change and higher reopen rates." },
    review: { calcTest: "passed", domainReview: "support operations lead (synthetic)", economicReview: "labour economics reviewer (synthetic)", version: "1.0", extraction: "Extraction by language model logged: model nova-lite-v1, prompt set KW-01-p1, 2026-09-12; all numeric inputs verified by hand" },
    limitations: ["Effect measured over 12 months; decay or further learning beyond that is not observed", "Redeployment share is the least supported input and controls half the swing", "External validity limited to advisory (not autonomous) deployments"] },

  /* ------------------------------------------------------------------ 2 */
  { id: "LS-02", industry: "Healthcare and life sciences", appClass: "Scientific discovery and design", level: "Product",
    title: "AI-assisted small-molecule discovery programmes",
    question: "Did an AI-assisted discovery platform shorten the time from target to development candidate, and what is that head start worth, for a portfolio of eight programmes against sixteen matched conventional programmes?",
    intendedUse: "Valuation of a platform company; milestone and royalty negotiation.",
    unit: "Product: discovery programme (target to development candidate)", unitRationale: "Time to candidate is observable per programme; clinical success is not yet observable for these cohorts and is carried as a scenario.",
    period: "2021 to 2026", geography: "Global", status: "Reviewed", synthetic: true,
    calibration: "Durations calibrated to public ranges for discovery timelines (roughly 3 to 5 years conventionally). Programme economics synthetic.",
    treatment: { system: "Generative chemistry and property prediction platform", version: "platform release 4 (2023) and 5 (2025)", deployed: "2021-09-01", scope: "8 programmes", autonomy: "Advisory to medicinal chemists", data: "Public and proprietary assay data", users: "Discovery teams", complements: ["Automated synthesis lab", "Larger early screening budget"] },
    comparator: { rank: 4, label: "Matched conventional programmes (same target class, modality and start window)", basis: "Sixteen programmes matched on target class, modality, company size and start year.", contamination: ["Matched programmes did not use the platform (checked against vendor list)", "Two matched programmes used other AI tools and were excluded"] },
    timeline: [["2021-09-01", "Platform adopted", "deployment"], ["2023-02-01", "Release 4", "version"], ["2024-06-01", "First candidate nominated", "economic"], ["2025-04-01", "Release 5", "version"]],
    technical: { outcome: "Months from target selection to development candidate", unit: "months", baseline: 46 },
    identification: { method: "survival", grade: "C", data: { treated: [{ t: 30, censored: false }, { t: 34, censored: false }, { t: 27, censored: false }, { t: 41, censored: false }, { t: 36, censored: false }, { t: 44, censored: true }, { t: 31, censored: false }, { t: 38, censored: true }],
      control: [{ t: 44, censored: false }, { t: 52, censored: false }, { t: 39, censored: false }, { t: 48, censored: false }, { t: 61, censored: true }, { t: 43, censored: false }, { t: 50, censored: false }, { t: 46, censored: false }, { t: 55, censored: true }, { t: 42, censored: false }, { t: 47, censored: false }, { t: 58, censored: true }, { t: 40, censored: false }, { t: 49, censored: false }, { t: 45, censored: false }, { t: 53, censored: false }] },
      assumptions: ["Matched programmes face the same hazard absent the platform", "Censoring is non-informative (ongoing programmes are not systematically slower)", "Candidate quality is comparable (tested with a separate attrition scenario)"],
      threats: ["Selection: easier targets may have been assigned to the platform (addressed by matching on target class, residual risk disclosed)", "The automated lab is a complement whose effect cannot be separated (combined-system effect reported)", "Survivorship: failed programmes leave no candidate date (both arms include censored programmes)"],
      preTrends: "Not applicable; cohort comparison. Balance table on five covariates shows standardised differences under 0.2." },
    evidence: [syn("E-LS-1", "Programme start and candidate dates for 24 programmes", "C", "Synthetic portfolio register, matched design"), syn("E-LS-2", "Discovery burn rate $1.4m per programme per year", "D", "Synthetic budget"),
               syn("E-LS-3", "Platform licence $2.6m per year across the portfolio; automated lab $4m capital", "D", "Synthetic contracts"), syn("E-LS-4", "Risk-adjusted candidate value $18m at nomination (industry-range calibration)", "D", "Synthetic valuation memo"),
               syn("E-LS-5", "Investor presentation: platform cuts discovery time in half", "E", "Company presentation"), syn("E-LS-6", "Preclinical attrition 62 percent conventional versus 66 percent platform in early data", "C", "Synthetic attrition tracker")],
    variables: [
      { id: "programmes", name: "Programmes per year reaching candidate", value: 2.2, unit: "per year", evidence: ["E-LS-1"], inference: "Eight programmes over the window" },
      { id: "burn", name: "Discovery cost per programme per month", value: 116667, unit: "$", evidence: ["E-LS-2"], inference: "$1.4m per year", low: 100000, high: 135000, adverse: "high" },
      { id: "candValue", name: "Risk-adjusted value of a candidate at nomination", value: 18000000, unit: "$", evidence: ["E-LS-4"], inference: "Industry-range calibration", low: 10000000, high: 26000000 },
      { id: "monthlyCoc", name: "Monthly cost of capital applied to earlier nomination", value: 0.0095, unit: "share", evidence: ["E-LS-4"], inference: "12 percent annual", low: 0.008, high: 0.012 },
      { id: "licence", name: "Platform licence per year", value: 2600000, unit: "$", evidence: ["E-LS-3"], inference: "Contract", low: 2200000, high: 3000000, adverse: "high" },
      { id: "labCapital", name: "Automated lab (complement, one-off)", value: 4000000, unit: "$", evidence: ["E-LS-3"], inference: "Included because the combined system is what was observed" },
      { id: "attritionDelta", name: "Extra preclinical attrition with platform candidates", value: 0.04, unit: "share", evidence: ["E-LS-6"], inference: "66 minus 62 percent, early and noisy", low: -0.03, high: 0.10, adverse: "high" },
      { id: "claimShare", name: "Claimed time saving", value: 0.5, unit: "share", evidence: ["E-LS-5"], inference: "Investor presentation, grade E" },
      { id: "baseProfitYear", name: "Portfolio contribution without AI", value: 12000000, unit: "$", evidence: ["E-LS-4"], inference: "Synthetic" }
    ],
    model: { horizonYears: 4, discountRate: 0.12, headStartYears: 4, rampYears: 1,
      channels: { revenue: "-effect * programmes * candValue * monthlyCoc", variableCost: "effect * programmes * burn", fixedCost: "licence", capital: "labCapital",
                  expectedLoss: "attritionDelta * programmes * candValue", baseProfit: "baseProfitYear" },
      note: "effect is the change in months to candidate (negative means faster). Earlier nomination earns the candidate's value sooner (a timing gain priced at the monthly cost of capital) and avoids burn; extra attrition is an expected loss.",
      claimedValue: "claimShare * 46 * programmes * (burn + candValue * monthlyCoc) * 4", contributionDenominator: "baseProfitYear * 4",
      welfare: [{ label: "Patients: earlier candidate availability", formula: "-effect", who: "patients", note: "Months earlier a candidate exists; realised patient benefit depends on clinical success not yet observed" }] },
    alternatives: [{ id: "naive", label: "All platform programmes versus all industry programmes (no matching)", rank: 5, method: "survival", effectScale: 1.6, data: { treated: [{ t: 30, censored: false }, { t: 34, censored: false }, { t: 27, censored: false }, { t: 41, censored: false }, { t: 36, censored: false }, { t: 44, censored: true }, { t: 31, censored: false }, { t: 38, censored: true }], control: [{ t: 44, censored: false }, { t: 52, censored: false }, { t: 39, censored: false }, { t: 48, censored: false }, { t: 61, censored: true }, { t: 43, censored: false }, { t: 50, censored: false }, { t: 46, censored: false }, { t: 55, censored: true }, { t: 42, censored: false }, { t: 47, censored: false }, { t: 58, censored: true }, { t: 40, censored: false }, { t: 49, censored: false }, { t: 45, censored: false }, { t: 53, censored: false }] }, note: "Unmatched comparison overstates the saving because platform programmes skew to tractable targets" }],
    assumptionWorlds: [{ label: "Attrition penalty at the top of its range (10 points)", overrides: { attritionDelta: 0.10 }, note: "Faster candidates that fail more often" }, { label: "Release 5 only (later programmes, smaller sample)", overrides: { effect: -14 }, note: "Later programmes show larger time savings but there are four of them" }],
    distribution: { subgroups: [{ label: "Kinase targets", effect: -16 }, { label: "GPCR targets", effect: -9 }, { label: "Novel target class", effect: 2 }], note: "Novel targets show no saving: the platform's advantage depends on prior data." },
    review: { calcTest: "passed", domainReview: "medicinal chemistry reviewer (synthetic)", economicReview: "biotech valuation reviewer (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set LS-02-p1, 2026-09-12" },
    limitations: ["Clinical outcomes are not observed; attrition is early", "The automated lab cannot be separated from the platform (combined-system effect)", "Matching on target class leaves residual selection"] },

  /* ------------------------------------------------------------------ 3 */
  { id: "MT-03", industry: "Healthcare and life sciences", appClass: "Prediction and classification", level: "Workflow",
    title: "AI reading assistance in a hospital imaging department",
    question: "Did AI-assisted reading change throughput, reimbursement and expected patient harm across four hospital sites, and does the department gain or lose once false negatives are priced?",
    intendedUse: "Product liability and hospital procurement decision; consumer claim about diagnostic accuracy.",
    unit: "Workflow: studies read per radiologist day; missed-finding rate", unitRationale: "Both throughput and error are measured per study at the site level.",
    period: "2025-Q3 to 2026-Q2", geography: "United States", status: "Reviewed", synthetic: true,
    calibration: "Throughput and error rates are synthetic within published ranges for assisted reading. No real device or hospital is described.",
    treatment: { system: "Triage and detection assistant for a single imaging modality", version: "software 3.1, sensitivity threshold 0.82", deployed: "2025-10-01", scope: "Two of four sites first; remaining two in 2026-02", autonomy: "Advisory with mandatory radiologist sign-off", data: "Vendor-trained model, no local retraining", users: "38 radiologists", complements: ["Worklist prioritisation change", "Two additional reading stations"] },
    comparator: { rank: 2, label: "Phased deployment: two sites awaiting the system", basis: "Same modality, staffing model and payer mix across sites.", contamination: ["Radiologists rotate across sites: reads assigned to the site of the study, exposure logged", "Reading-station addition happened at all sites (a complement common to both arms)"] },
    timeline: [["2025-08-01", "Vendor claim: 30 percent faster reads, no loss in accuracy", "claim"], ["2025-10-01", "Sites A and B live", "deployment"], ["2026-01-15", "Threshold changed from 0.85 to 0.82", "version"], ["2026-02-01", "Sites C and D live", "deployment"]],
    technical: { outcome: "Studies read per radiologist day", unit: "studies per day", baseline: 58 },
    identification: { method: "did", grade: "B", data: { treated: { pre: [57.5, 58.2, 58.0, 58.6, 57.9, 58.3], post: [64.8, 66.1, 66.9, 67.2, 66.8, 67.0] }, control: { pre: [57.8, 58.1, 58.3, 58.4, 58.2, 58.5], post: [59.0, 59.4, 59.6, 59.8, 59.5, 59.9] } },
      assumptions: ["Parallel trends across sites", "Case mix stable (checked on modality and age bands)", "Missed findings measured by the same 90-day follow-up rule in both arms"],
      threats: ["Automation bias: radiologists agree with the assistant on marginal findings (tested through subgroup: findings near threshold)", "Extra reading stations lift throughput at all sites (common to both arms, removed by the design)", "Threshold change in month four is a new treatment (assumption world)"],
      preTrends: "Pre-period slopes 0.11 (treated) and 0.11 (control) studies per month." },
    evidence: [syn("E-MT-1", "Studies per radiologist day by site, 6 pre and 6 post months", "D", "Synthetic RIS export"), syn("E-MT-2", "90-day missed-finding audit: 0.36 percent with assistant versus 0.30 percent without on 41,000 studies", "B", "Synthetic audit with blinded second read"),
               syn("E-MT-3", "Average reimbursement per incremental study $84; marginal cost per study $19", "D", "Synthetic finance summary"), syn("E-MT-4", "Expected cost per missed finding $6,000 once severity mix is applied (most missed findings are low severity; the tail carries claims and remediation), industry-range calibration", "C", "Synthetic actuarial memo"),
               syn("E-MT-5", "Software licence $310,000 per year; integration $220,000", "D", "Synthetic contract"), syn("E-MT-6", "Vendor claim: 30 percent faster with no loss of accuracy", "E", "Vendor brochure"), pub(PUB.ftc, "Press release")],
    variables: [
      { id: "radiologists", name: "Radiologists", value: 38, unit: "people", evidence: ["E-MT-1"], inference: "Rota" },
      { id: "days", name: "Reading days per radiologist per year", value: 215, unit: "days", evidence: ["E-MT-1"], inference: "Rota less leave", low: 200, high: 225 },
      { id: "capture", name: "Share of extra capacity that becomes billed studies", value: 0.6, unit: "share", evidence: ["E-MT-3"], inference: "Backlog and referral growth absorb 60 percent", low: 0.3, high: 0.9, adverse: "low" },
      { id: "reimb", name: "Contribution per incremental study", value: 65, unit: "$", evidence: ["E-MT-3"], inference: "$84 reimbursement less $19 marginal cost", low: 50, high: 80 },
      { id: "studiesYear", name: "Studies per year in scope", value: 474000, unit: "studies", evidence: ["E-MT-1"], inference: "38 × 215 × 58 at baseline" },
      { id: "missDelta", name: "Extra missed-finding rate with the assistant", value: 0.0006, unit: "share", evidence: ["E-MT-2"], inference: "0.36 minus 0.30 percent", low: 0.0001, high: 0.0012, adverse: "high" },
      { id: "missCost", name: "Expected cost per missed finding", value: 6000, unit: "$", evidence: ["E-MT-4"], inference: "Actuarial calibration, severity weighted", low: 2500, high: 15000, adverse: "high" },
      { id: "licence", name: "Licence per year", value: 310000, unit: "$", evidence: ["E-MT-5"], inference: "Contract" },
      { id: "integration", name: "Integration (one-off)", value: 220000, unit: "$", evidence: ["E-MT-5"], inference: "Invoice" },
      { id: "claimedSpeed", name: "Vendor-claimed speed gain", value: 0.30, unit: "share", evidence: ["E-MT-6"], inference: "Grade E" },
      { id: "baseProfitYear", name: "Department contribution without AI", value: 6100000, unit: "$", evidence: ["E-MT-3"], inference: "Synthetic" }
    ],
    model: { horizonYears: 3, discountRate: 0.08, headStartYears: 3, rampYears: 1,
      channels: { revenue: "effect * radiologists * days * capture * reimb", fixedCost: "licence", capital: "integration", expectedLoss: "missDelta * studiesYear * missCost", baseProfit: "baseProfitYear" },
      note: "effect is extra studies per radiologist day. Expected patient harm is priced as an expected loss and reported separately as welfare because the hospital bears only part of it.",
      claimedValue: "claimedSpeed * 58 * radiologists * days * capture * reimb * 3", contributionDenominator: "baseProfitYear * 3",
      welfare: [{ label: "Patients: expected additional missed findings per year", formula: "missDelta * studiesYear", who: "patients", note: "Count of additional missed findings; the harm to patients exceeds the hospital's expected loss" },
                { label: "Patients: faster turnaround (share)", formula: "effect / 58", who: "patients", note: "Nonprice benefit" }] },
    alternatives: [{ id: "prepost", label: "Sites A and B before and after only", rank: 3, method: "did", data: { treated: { pre: [57.5, 58.2, 58.0, 58.6, 57.9, 58.3], post: [64.8, 66.1, 66.9, 67.2, 66.8, 67.0] }, control: { pre: [1, 1, 1, 1, 1, 1], post: [1, 1, 1, 1, 1, 1] } }, note: "Attributes the station-driven 1.4 study gain to the assistant" }],
    assumptionWorlds: [{ label: "Threshold 0.85 retained (months one to three only)", overrides: { effect: 6.1, missDelta: 0.0003 }, note: "Higher threshold: fewer flags, fewer misses, smaller speed gain" }, { label: "Missed-finding cost at the top of its range", overrides: { missCost: 15000 }, note: "Litigation-heavy environment" }],
    distribution: { subgroups: [{ label: "Findings far from threshold", effect: 0.0 }, { label: "Findings near threshold (automation bias)", effect: -0.0019 }, { label: "Patients over 75", effect: -0.0011 }], note: "Subgroup effects are changes in missed-finding rate; the average conceals a concentrated harm near the threshold and in older patients." },
    review: { calcTest: "passed", domainReview: "radiology quality lead (synthetic)", economicReview: "health economics reviewer (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set MT-03-p1, 2026-09-12" },
    limitations: ["Missed findings observed over 90 days; longer-horizon harm not measured", "Cost per missed finding is a calibrated range, not observed claims", "Result applies to the advisory configuration with sign-off"] },

  /* ------------------------------------------------------------------ 4 */
  { id: "SC-04", industry: "Semiconductors and electronics", appClass: "Monitoring and anomaly detection", level: "Product",
    title: "AI defect inspection on a wafer-fabrication line",
    question: "What is the value of an AI inspection model on one fabrication line, through yield, scrap and inspection throughput, compared with the conventional rule-based inspection tool on a matched line?",
    intendedUse: "Capital allocation decision and patent apportionment (inspection feature versus full tool).",
    unit: "Product: line-level yield and throughput", unitRationale: "Yield is measured per lot; both lines run the same product mix.",
    period: "2025-Q2 to 2026-Q2", geography: "Asia and United States", status: "Reviewed", synthetic: true,
    calibration: "Yield changes of about one percentage point are within ranges reported for inspection upgrades. All line economics are synthetic.",
    treatment: { system: "Deep-learning defect classification on optical inspection images", version: "model 7, retrained quarterly", deployed: "2025-06-15", scope: "Line 3 (Line 4 conventional)", autonomy: "Autonomous classification; engineers review only escalations", data: "18 months of labelled inspection images", users: "Yield engineering", complements: ["Camera upgrade on Line 3 only", "Recipe change in 2025-09 on both lines"] },
    comparator: { rank: 4, label: "Matched line with the conventional inspection tool", basis: "Same product mix, tool generation and shift pattern; lines differ by camera upgrade (complement).", contamination: ["Recipe change applied to both lines on the same day", "Camera upgrade confounds Line 3 (reported as combined effect, engineering bound separates it)"] },
    timeline: [["2025-05-01", "Camera upgrade on Line 3", "complement"], ["2025-06-15", "Model 7 live on Line 3", "deployment"], ["2025-09-10", "Recipe change both lines", "concurrent"], ["2026-01-05", "Quarterly retrain", "version"]],
    technical: { outcome: "Line yield", unit: "percentage points", baseline: 91.2 },
    identification: { method: "did", grade: "C", data: { treated: { pre: [91.1, 91.3, 91.2, 91.4, 91.0, 91.3], post: [92.0, 92.3, 92.5, 92.6, 92.4, 92.7] }, control: { pre: [91.0, 91.2, 91.3, 91.2, 91.1, 91.4], post: [91.3, 91.4, 91.5, 91.6, 91.4, 91.6] } },
      assumptions: ["Parallel yield trends across lines absent the model", "Camera upgrade effect bounded by the engineering analysis (0.2 to 0.4 points)", "Product mix constant"],
      threats: ["Camera upgrade is a complement on the treated line only", "Recipe change: common to both, removed by the design", "Learning by engineers on Line 3 may carry to Line 4 (would understate the effect)"],
      preTrends: "Pre-period slopes 0.01 (treated) and 0.05 (control) yield points per month; the control line was drifting up slightly faster, which works against the estimate." },
    evidence: [syn("E-SC-1", "Monthly line yield, Lines 3 and 4", "D", "Synthetic MES export"), syn("E-SC-2", "Engineering study: camera upgrade alone worth 0.2 to 0.4 yield points", "D", "Synthetic engineering memo"),
               syn("E-SC-3", "Wafer starts 14,000 per month per line; contribution per good wafer $2,900", "D", "Synthetic finance summary"), syn("E-SC-4", "Model licence and compute $1.1m per year; camera $2.4m; integration $0.9m", "D", "Synthetic capital request"),
               syn("E-SC-5", "Escalation review time fell 31 percent; false escalations rose in month one then normalised", "C", "Synthetic engineering log"), syn("E-SC-6", "Customer quality-return exposure: model misclassification could pass a defective lot, estimated 0.6 events per year at $450,000", "C", "Synthetic quality risk register")],
    variables: [
      { id: "starts", name: "Wafer starts per year", value: 168000, unit: "wafers", evidence: ["E-SC-3"], inference: "14,000 per month" },
      { id: "contribution", name: "Contribution per good wafer", value: 2900, unit: "$", evidence: ["E-SC-3"], inference: "Price less variable cost", low: 2400, high: 3400 },
      { id: "cameraShare", name: "Share of the observed gain due to the camera upgrade", value: 0.25, unit: "share", evidence: ["E-SC-2"], inference: "0.3 of 1.2 points from the engineering memo", low: 0.15, high: 0.35, adverse: "high" },
      { id: "licence", name: "Model licence and compute per year", value: 1100000, unit: "$", evidence: ["E-SC-4"], inference: "Contract" },
      { id: "capital", name: "Integration (one-off, AI-specific)", value: 900000, unit: "$", evidence: ["E-SC-4"], inference: "Camera excluded: attributed to the complement" },
      { id: "reviewSaving", name: "Engineering review hours saved per year", value: 2100, unit: "hours", evidence: ["E-SC-5"], inference: "31 percent of 6,800 hours", low: 1500, high: 2600 },
      { id: "engRate", name: "Engineering hour cost", value: 95, unit: "$", evidence: ["E-SC-5"], inference: "Loaded rate" },
      { id: "passEvents", name: "Defective lots passed per year", value: 0.6, unit: "events", evidence: ["E-SC-6"], inference: "Risk register", low: 0.2, high: 1.5, adverse: "high" },
      { id: "passCost", name: "Cost per passed defective lot", value: 450000, unit: "$", evidence: ["E-SC-6"], inference: "Returns and requalification", low: 250000, high: 800000, adverse: "high" },
      { id: "baseProfitYear", name: "Line contribution without AI", value: 44000000, unit: "$", evidence: ["E-SC-3"], inference: "Synthetic" }
    ],
    model: { horizonYears: 4, discountRate: 0.10, headStartYears: 3, rampYears: 1,
      channels: { revenue: "(effect / 100) * (1 - cameraShare) * starts * contribution", variableCost: "-(reviewSaving * engRate)", fixedCost: "licence", capital: "capital", expectedLoss: "passEvents * passCost", baseProfit: "baseProfitYear" },
      note: "effect is yield points. The camera share is stripped out so the AI-only effect is valued; the combined-system effect appears as an assumption world. Head start of three years: the conventional tool vendor ships comparable classification in year four.",
      contributionDenominator: "baseProfitYear * 4",
      welfare: [{ label: "Customers: lots passed with latent defects", formula: "passEvents", who: "customers", note: "Count per year; priced to the fab as expected loss, borne partly downstream" }] },
    alternatives: [{ id: "combined", label: "Combined system (camera plus model) attributed to AI", rank: 4, method: "did", data: { treated: { pre: [91.1, 91.3, 91.2, 91.4, 91.0, 91.3], post: [92.0, 92.3, 92.5, 92.6, 92.4, 92.7] }, control: { pre: [91.0, 91.2, 91.3, 91.2, 91.1, 91.4], post: [91.3, 91.4, 91.5, 91.6, 91.4, 91.6] } }, effectScale: 1.0, note: "Same estimate but with cameraShare treated as zero in the assumption world below" },
                   { id: "bound", label: "Engineering bound (no field comparison)", rank: 6, method: "bound", data: { low: 0.3, high: 0.9, basis: "Defect capture rate difference translated through the yield model", calibration: "Bench tests on 2,000 labelled images" }, note: "Used if the matched line were unavailable" }],
    assumptionWorlds: [{ label: "Camera share zero (combined-system effect)", overrides: { cameraShare: 0 }, note: "What the fab actually experienced, including the complement" }, { label: "Head start one year (competitor tool ships early)", overrides: { headStartYears: 1 }, note: "Timing dominates: most value is the head start" }],
    distribution: { subgroups: [{ label: "Mature process nodes", effect: 1.4 }, { label: "New node ramp", effect: 0.3 }], note: "Gain concentrates on mature nodes where the labelled image history is deep." },
    review: { calcTest: "passed", domainReview: "yield engineering reviewer (synthetic)", economicReview: "industrial economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set SC-04-p1, 2026-09-12" },
    limitations: ["The camera share is an engineering estimate, not observed", "Yield effect measured over one year on one line", "Head-start length is a judgement about competitor tools"] },

  /* ------------------------------------------------------------------ 5 */
  { id: "MF-05", industry: "Manufacturing and industrial systems", appClass: "Prediction and classification", level: "Business unit",
    title: "Predictive maintenance across a plant network",
    question: "Did predictive maintenance reduce unplanned downtime across six plants, after the implementation dip, compared with six matched plants on scheduled maintenance?",
    intendedUse: "Valuation of an industrial AI business unit; M&A diligence on claimed savings.",
    unit: "Business unit: six plants", unitRationale: "Downtime and maintenance cost are tracked per plant per month.",
    period: "2024-Q3 to 2026-Q2", geography: "North America", status: "Reviewed", synthetic: true,
    calibration: "The short-run implementation loss follows the productivity J-curve finding in the Census industrial AI paper; magnitudes synthetic.",
    treatment: { system: "Vibration and thermal anomaly models with work-order integration", version: "platform 2.0", deployed: "2024-10-01", scope: "Six plants", autonomy: "Advisory to maintenance planners", data: "Sensor retrofits on 1,200 assets", users: "Maintenance planners", complements: ["Sensor retrofit capital", "Planner retraining", "Spare-parts policy change"] },
    comparator: { rank: 4, label: "Six matched plants on scheduled maintenance", basis: "Matched on asset age, product line and utilisation.", contamination: ["Spare-parts policy change applied to treated plants only (part of the treatment package)", "One control plant had a fire in 2025-03: excluded"] },
    timeline: [["2024-10-01", "Platform live", "deployment"], ["2024-10-01", "Implementation dip begins (false alarms, planner learning)", "economic"], ["2025-04-01", "Alarm thresholds tuned", "version"], ["2025-09-01", "Spare-parts policy change", "complement"]],
    technical: { outcome: "Unplanned downtime hours per plant per month", unit: "hours", baseline: 62 },
    identification: { method: "did", grade: "C", data: { treated: { pre: [61, 63, 62, 64, 61, 63], post: [69, 66, 60, 54, 49, 46, 44, 43, 42, 43, 41, 42] }, control: { pre: [60, 62, 61, 63, 60, 62], post: [61, 62, 60, 63, 61, 62, 60, 62, 61, 62, 60, 61] } },
      assumptions: ["Parallel downtime trends", "Spare-parts policy is part of the treatment package (combined-system effect reported)", "Fire-affected plant excluded from control does not bias the remainder"],
      threats: ["J-curve: the first six post months show more downtime, not less; averaging over the full window understates the steady state and truncating it overstates value", "Planner attention shifted to treated plants (Hawthorne)", "Sensor retrofit itself may reveal defects (part of the package)"],
      preTrends: "Pre-period slopes 0.17 (treated) and 0.17 (control) hours per month; no gap." },
    evidence: [pub(PUB.jcurve, "Abstract"), syn("E-MF-1", "Monthly unplanned downtime hours by plant", "D", "Synthetic CMMS export"), syn("E-MF-2", "Cost of downtime $9,400 per hour (lost contribution plus overtime)", "D", "Synthetic finance memo"),
               syn("E-MF-3", "Sensor retrofit $3.1m; platform $1.5m per year; retraining $0.4m", "D", "Synthetic capital request"), syn("E-MF-4", "False-alarm work orders cost $610,000 in the first six months", "C", "Synthetic work-order audit"),
               syn("E-MF-5", "Board deck: 40 percent downtime reduction", "E", "Company presentation"), syn("E-MF-6", "Cyber assessment: connected sensors add an estimated 2 percent annual probability of an OT incident costing $4m", "C", "Synthetic risk assessment")],
    variables: [
      { id: "plants", name: "Plants", value: 6, unit: "plants", evidence: ["E-MF-1"], inference: "Scope" },
      { id: "downtimeCost", name: "Cost per downtime hour", value: 9400, unit: "$", evidence: ["E-MF-2"], inference: "Lost contribution plus overtime", low: 7000, high: 12000 },
      { id: "platform", name: "Platform per year", value: 1500000, unit: "$", evidence: ["E-MF-3"], inference: "Contract" },
      { id: "capital", name: "Sensors and retraining (one-off)", value: 3500000, unit: "$", evidence: ["E-MF-3"], inference: "Capital request" },
      { id: "falseAlarms", name: "False-alarm cost in the implementation period (one-off)", value: 610000, unit: "$", evidence: ["E-MF-4"], inference: "Work-order audit", low: 400000, high: 900000, adverse: "high" },
      { id: "cyberProb", name: "Added annual probability of an OT incident", value: 0.02, unit: "share", evidence: ["E-MF-6"], inference: "Risk assessment", low: 0.005, high: 0.05, adverse: "high" },
      { id: "cyberCost", name: "Cost of an OT incident", value: 4000000, unit: "$", evidence: ["E-MF-6"], inference: "Risk assessment", low: 2000000, high: 8000000, adverse: "high" },
      { id: "claimedCut", name: "Claimed downtime reduction", value: 0.40, unit: "share", evidence: ["E-MF-5"], inference: "Grade E" },
      { id: "baseProfitYear", name: "Plant network contribution without AI", value: 58000000, unit: "$", evidence: ["E-MF-2"], inference: "Synthetic" }
    ],
    model: { horizonYears: 4, discountRate: 0.09, headStartYears: 4, rampYears: 2,
      channels: { variableCost: "effect * 12 * plants * downtimeCost", fixedCost: "platform", capital: "capital + falseAlarms", expectedLoss: "cyberProb * cyberCost", baseProfit: "baseProfitYear" },
      note: "effect is the change in downtime hours per plant per month (negative is better) averaged over the full post window, which includes the implementation dip. A two-year ramp reflects the observed learning curve; the one-off false-alarm cost is booked with capital.",
      claimedValue: "claimedCut * 62 * 12 * plants * downtimeCost * 4", contributionDenominator: "baseProfitYear * 4",
      welfare: [{ label: "Workers: overtime hours removed", formula: "-effect * 12 * plants * 0.4", who: "workers", note: "Fewer emergency call-outs; not a cash flow to the firm beyond the overtime already counted" }] },
    alternatives: [{ id: "steady", label: "Steady state only (months 7 to 12)", rank: 4, method: "did", data: { treated: { pre: [61, 63, 62, 64, 61, 63], post: [44, 43, 42, 43, 41, 42] }, control: { pre: [60, 62, 61, 63, 60, 62], post: [60, 62, 61, 62, 60, 61] } }, note: "Ignores the dip; overstates the first year" },
                   { id: "dip", label: "Implementation period only (months 1 to 6)", rank: 4, method: "did", data: { treated: { pre: [61, 63, 62, 64, 61, 63], post: [69, 66, 60, 54, 49, 46] }, control: { pre: [60, 62, 61, 63, 60, 62], post: [61, 62, 60, 63, 61, 62] } }, note: "What a six-month review would have concluded: a loss" }],
    assumptionWorlds: [{ label: "Threshold tuning in month six treated as the start of the treatment", overrides: { effect: -19 }, note: "Later steady state" }],
    distribution: { subgroups: [{ label: "Rotating equipment", effect: -26 }, { label: "Conveyors", effect: -14 }, { label: "Electrical switchgear", effect: 3 }], note: "Switchgear alarms were mostly false; the model adds work there." },
    review: { calcTest: "passed", domainReview: "reliability engineering reviewer (synthetic)", economicReview: "industrial economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set MF-05-p1, 2026-09-12" },
    limitations: ["Twelve post months; durability of the steady state unobserved", "Spare-parts policy cannot be separated", "Cyber risk is an assessed probability, not observed frequency"] },

  /* ------------------------------------------------------------------ 6 */
  { id: "FS-06", industry: "Financial services and insurance", appClass: "Prediction and classification", level: "Product",
    title: "AI underwriting model for small-business loans",
    question: "Did replacing a scorecard with a machine-learning underwriting model change approval, loss and review cost for applicants near the decision threshold, and what is the portfolio value once fairness review cost and conduct risk are included?",
    intendedUse: "Regulatory inquiry into model fairness; internal model risk review; investor question on credit quality.",
    unit: "Product: loan applications near the score threshold", unitRationale: "The model changed decisions only near the threshold; a regression discontinuity isolates that margin.",
    period: "2025-Q1 to 2026-Q2", geography: "United States", status: "Reviewed", synthetic: true,
    calibration: "Loss rates and spreads synthetic within ranges typical of small-business lending. No lender is described.",
    treatment: { system: "Gradient-boosted underwriting model replacing a logistic scorecard", version: "model 2025.1, threshold score 620", deployed: "2025-01-15", scope: "All new applications", autonomy: "Autonomous approve or decline; manual review band 600 to 640", data: "Bureau, cash-flow and application data", users: "Underwriting", complements: ["Cash-flow data feed (new)", "Smaller manual review team"] },
    comparator: { rank: 1, label: "Threshold design: applicants just above and below the model's cutoff", basis: "Applicants within 40 points of the cutoff are comparable except for the decision.", contamination: ["No manipulation at the cutoff (density test on scores)", "Manual review band overlaps the bandwidth: reviewed loans flagged"] },
    timeline: [["2025-01-15", "Model live", "deployment"], ["2025-06-01", "Fairness review opened after disparity finding", "risk"], ["2025-10-01", "Threshold moved 620 to 615", "version"]],
    technical: { outcome: "12-month default rate at the margin", unit: "share", baseline: 0.071 },
    identification: { method: "rdd", grade: "B", data: { cutoff: 620, bandwidth: 40, obs: (function () { var r = seeded(606), o = []; for (var i = 0; i < 400; i++) { var x = 580 + r() * 80; var y = 0.11 - 0.0011 * (x - 580) + (x >= 620 ? -0.021 : 0) + (r() - 0.5) * 0.02; o.push({ x: +x.toFixed(1), y: +y.toFixed(4) }); } return o; })() },
      assumptions: ["No manipulation of scores at the cutoff", "Outcomes vary smoothly with score absent the decision", "Loans approved at the margin are comparable in size"],
      threats: ["Narrow external validity: the effect holds near the threshold only", "Manual review band contaminates part of the bandwidth", "Disparate impact: approval rates by protected class differ near the cutoff (reported, not netted)"],
      preTrends: "Not applicable. Density test: no bunching at 620." },
    evidence: [syn("E-FS-1", "400 marginal loans with score and 12-month default flag", "B", "Synthetic loan tape, threshold design"), syn("E-FS-2", "Average marginal loan $85,000; net spread 6.2 percent; loss given default 55 percent", "D", "Synthetic portfolio summary"),
               syn("E-FS-3", "Marginal approvals per year 3,800; manual review cost $140 per file removed on 2,200 files", "D", "Synthetic operations summary"), syn("E-FS-4", "Model licence and monitoring $900,000 per year; build $1.6m", "D", "Synthetic budget"),
               syn("E-FS-5", "Fairness review: approval gap of 4 points for one protected class near the cutoff; remediation and counsel cost $1.2m; residual regulatory exposure estimated 10 percent probability of a $6m outcome", "C", "Synthetic compliance memo"), pub(PUB.sec, "Statement")],
    variables: [
      { id: "approvals", name: "Marginal approvals per year", value: 3800, unit: "loans", evidence: ["E-FS-3"], inference: "Volume in the bandwidth" },
      { id: "loan", name: "Average marginal loan", value: 85000, unit: "$", evidence: ["E-FS-2"], inference: "Portfolio summary" },
      { id: "lgd", name: "Loss given default", value: 0.55, unit: "share", evidence: ["E-FS-2"], inference: "Portfolio summary", low: 0.45, high: 0.65 },
      { id: "reviewSaving", name: "Manual review cost avoided per year", value: 308000, unit: "$", evidence: ["E-FS-3"], inference: "2,200 files × $140", low: 200000, high: 360000 },
      { id: "licence", name: "Licence and monitoring per year", value: 900000, unit: "$", evidence: ["E-FS-4"], inference: "Budget" },
      { id: "build", name: "Build (one-off)", value: 1600000, unit: "$", evidence: ["E-FS-4"], inference: "Budget" },
      { id: "remediation", name: "Fairness remediation (one-off)", value: 1200000, unit: "$", evidence: ["E-FS-5"], inference: "Compliance memo" },
      { id: "regProb", name: "Annual probability of a regulatory outcome", value: 0.10, unit: "share", evidence: ["E-FS-5"], inference: "Compliance memo", low: 0.03, high: 0.25, adverse: "high" },
      { id: "regCost", name: "Cost of that outcome", value: 6000000, unit: "$", evidence: ["E-FS-5"], inference: "Compliance memo", low: 2000000, high: 12000000, adverse: "high" },
      { id: "baseProfitYear", name: "Marginal book contribution without AI", value: 14000000, unit: "$", evidence: ["E-FS-2"], inference: "Synthetic" }
    ],
    model: { horizonYears: 3, discountRate: 0.10, headStartYears: 3, rampYears: 1,
      channels: { revenue: "-effect * approvals * loan * lgd", variableCost: "-reviewSaving", fixedCost: "licence", capital: "build + remediation", expectedLoss: "regProb * regCost", baseProfit: "baseProfitYear" },
      note: "effect is the change in default rate at the margin (negative is better); the credit benefit is avoided loss = -effect × approvals × loan × LGD. Spread is unchanged at the margin by construction, so no revenue channel beyond avoided loss.",
      contributionDenominator: "baseProfitYear * 3",
      welfare: [{ label: "Applicants: approval-rate gap for one protected class near the cutoff (points)", formula: "4", who: "applicants", note: "Distributional effect reported separately; not netted against profit" },
                { label: "Borrowers: fewer defaults at the margin per year", formula: "-effect * approvals", who: "borrowers", note: "Avoided distress events" }] },
    alternatives: [{ id: "wide", label: "Wide bandwidth (80 points)", rank: 1, method: "rdd", data: { cutoff: 620, bandwidth: 80, obs: (function () { var r = seeded(606), o = []; for (var i = 0; i < 400; i++) { var x = 580 + r() * 80; var y = 0.11 - 0.0011 * (x - 580) + (x >= 620 ? -0.021 : 0) + (r() - 0.5) * 0.02; o.push({ x: +x.toFixed(1), y: +y.toFixed(4) }); } return o; })() }, note: "Same data, wider window: more precision, more bias" },
                   { id: "adopter", label: "Adopter versus non-adopter lenders (no design)", rank: 5, method: "scenario", data: { central: -0.030, low: -0.06, high: 0.0, scenarios: ["Industry comparison of adopters and non-adopters, uncontrolled"] }, note: "Selection: adopters were better lenders before adopting" }],
    assumptionWorlds: [{ label: "Threshold moved to 615 (post October 2025)", overrides: { effect: -0.017, approvals: 4300 }, note: "More approvals, slightly smaller loss improvement per loan" }],
    distribution: { subgroups: [{ label: "Applicants with cash-flow data", effect: -0.028 }, { label: "Thin-file applicants", effect: 0.004 }, { label: "One protected class", effect: -0.019 }], note: "Thin-file applicants see no credit-quality gain and a lower approval rate." },
    review: { calcTest: "passed", domainReview: "credit risk reviewer (synthetic)", economicReview: "financial economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set FS-06-p1, 2026-09-12" },
    limitations: ["Effect is local to the threshold", "Regulatory exposure is an assessed probability", "Twelve-month defaults only"] },

  /* ------------------------------------------------------------------ 7 */
  { id: "RT-07", industry: "Retail, consumer and ecommerce", appClass: "Optimisation and control", level: "Market",
    title: "Algorithmic pricing in a regional grocery chain",
    question: "What did an AI pricing system do to margin and volume in eight treated markets compared with six untreated markets, and what happened to consumer surplus?",
    intendedUse: "Antitrust inquiry into algorithmic pricing; class-impact analysis; internal decision on rollout.",
    unit: "Market: 14 regional markets", unitRationale: "Prices are set per market; volumes and margins are reported per market per month.",
    period: "2025-Q1 to 2026-Q2", geography: "United States", status: "Reviewed", synthetic: true,
    calibration: "Margin and elasticity ranges are synthetic; the competition concern follows the FTC and DOJ request for comment on algorithmic pricing.",
    treatment: { system: "Demand-model pricing engine with weekly re-optimisation", version: "engine 3, objective: gross margin", deployed: "2025-05-01", scope: "Eight markets in two waves", autonomy: "Autonomous within guardrails (max 6 percent move per week)", data: "Own sales, competitor scrape, weather", users: "Pricing team", complements: ["Electronic shelf labels in treated markets"] },
    comparator: { rank: 2, label: "Staggered market rollout: six markets awaiting deployment", basis: "Markets were scheduled by label-installation logistics, not by expected gain.", contamination: ["Cross-market shopping under 2 percent", "Shelf labels installed only in treated markets: complement, cost included"] },
    timeline: [["2025-05-01", "Wave one, four markets", "deployment"], ["2025-09-01", "Wave two, four markets", "deployment"], ["2026-02-23", "Regulators seek comment on algorithmic pricing", "risk"]],
    technical: { outcome: "Gross margin rate", unit: "percentage points", baseline: 27.5 },
    identification: { method: "did", grade: "B", data: { treated: { pre: [27.4, 27.6, 27.5, 27.7, 27.4, 27.6], post: [28.4, 28.9, 29.1, 29.3, 29.2, 29.4] }, control: { pre: [27.3, 27.5, 27.6, 27.5, 27.4, 27.6], post: [27.5, 27.7, 27.6, 27.8, 27.6, 27.7] } },
      assumptions: ["Parallel margin trends", "Rollout order unrelated to expected gain (installation logistics)", "Competitor responses in treated markets are part of the treatment effect"],
      threats: ["Volume loss: margin up, units down (volume channel modelled separately)", "Competitor algorithm interaction (tacit coordination risk is a welfare and legal question, reported)", "Shelf labels enable price changes and are a complement"],
      preTrends: "Pre-period slopes 0.02 (treated) and 0.03 (control) margin points per month." },
    evidence: [pub(PUB.ftcdoj, "Press release"), syn("E-RT-1", "Monthly gross margin rate and unit volume by market", "D", "Synthetic sales export"), syn("E-RT-2", "Unit volume fell 1.9 percent in treated markets relative to control", "C", "Synthetic volume analysis (same design)"),
               syn("E-RT-3", "Revenue per market $96m per year", "D", "Synthetic finance summary"), syn("E-RT-4", "Engine $2.2m per year; shelf labels $4.0m across eight markets", "D", "Synthetic capital request"),
               syn("E-RT-5", "Counsel memo: 8 percent annual probability of an antitrust action with expected cost $25m given the guardrails", "C", "Synthetic legal risk memo"), syn("E-RT-6", "Average price increase in treated markets 1.4 percent; own-price elasticity about -1.3", "C", "Synthetic demand estimate")],
    variables: [
      { id: "markets", name: "Treated markets", value: 8, unit: "markets", evidence: ["E-RT-1"], inference: "Scope" },
      { id: "revenue", name: "Revenue per market per year", value: 96000000, unit: "$", evidence: ["E-RT-3"], inference: "Finance summary" },
      { id: "volumeLoss", name: "Relative unit volume loss", value: 0.019, unit: "share", evidence: ["E-RT-2"], inference: "Same design on volume", low: 0.01, high: 0.035, adverse: "high" },
      { id: "baseMargin", name: "Gross margin rate without AI", value: 0.275, unit: "share", evidence: ["E-RT-1"], inference: "Control mean" },
      { id: "engine", name: "Engine per year", value: 2200000, unit: "$", evidence: ["E-RT-4"], inference: "Contract" },
      { id: "labels", name: "Shelf labels (complement, one-off)", value: 4000000, unit: "$", evidence: ["E-RT-4"], inference: "Included: the engine cannot operate without them" },
      { id: "actionProb", name: "Annual probability of an antitrust action", value: 0.08, unit: "share", evidence: ["E-RT-5"], inference: "Counsel memo", low: 0.02, high: 0.2, adverse: "high" },
      { id: "actionCost", name: "Expected cost given action", value: 25000000, unit: "$", evidence: ["E-RT-5"], inference: "Counsel memo", low: 10000000, high: 50000000, adverse: "high" },
      { id: "priceRise", name: "Average price increase", value: 0.014, unit: "share", evidence: ["E-RT-6"], inference: "Demand estimate", low: 0.008, high: 0.02 },
      { id: "baseProfitYear", name: "Treated markets contribution without AI", value: 61000000, unit: "$", evidence: ["E-RT-3"], inference: "Synthetic" }
    ],
    model: { horizonYears: 3, discountRate: 0.09, headStartYears: 3, rampYears: 1,
      channels: { revenue: "(effect / 100) * markets * revenue", cannibalization: "volumeLoss * markets * revenue * baseMargin", fixedCost: "engine", capital: "labels", expectedLoss: "actionProb * actionCost", baseProfit: "baseProfitYear" },
      note: "effect is margin points on revenue; the volume loss is booked as a cannibalisation line so it is not netted invisibly. Head start of three years: competitors are assumed to deploy comparable engines by year four (an assumption world tests a shorter head start).",
      contributionDenominator: "baseProfitYear * 3",
      welfare: [{ label: "Consumers: surplus change per year (overcharge on retained volume plus deadweight loss)", formula: "-(priceRise * markets * revenue + 0.5 * priceRise * volumeLoss * markets * revenue)", who: "consumers", note: "Private gain and consumer loss move in opposite directions; the two are never combined into one number" },
                { label: "Competitors: price response", formula: "0", who: "competitors", note: "Competitor prices rose 0.4 percent in treated markets; whether this is coordination is a legal question the system does not decide" }] },
    alternatives: [{ id: "wave2", label: "Wave two markets only (four markets, shorter window)", rank: 2, method: "did", data: { treated: { pre: [27.5, 27.6, 27.4, 27.7, 27.5, 27.6], post: [28.1, 28.5, 28.7] }, control: { pre: [27.3, 27.5, 27.6, 27.5, 27.4, 27.6], post: [27.6, 27.7, 27.6] } }, note: "Earlier in the learning curve" },
                   { id: "structural", label: "Structural demand model (no rollout variation)", rank: 5, method: "scenario", data: { central: 1.5, low: 0.8, high: 2.4, scenarios: ["Simulated margin under estimated demand and competitor response"] }, note: "Model-dependent; used to cross-check" }],
    assumptionWorlds: [{ label: "Guardrail tightened to 3 percent per week", overrides: { effect: 1.1, volumeLoss: 0.011, actionProb: 0.04 }, note: "Smaller margin gain, smaller volume loss, lower legal risk" }, { label: "Head start of one year (competitors respond fast)", overrides: { headStartYears: 1 }, note: "The engine pays for itself only if the lead lasts" }],
    distribution: { subgroups: [{ label: "High-income markets", effect: 2.3 }, { label: "Low-income markets", effect: 1.6 }, { label: "Price-sensitive categories", effect: 0.4 }], note: "Consumer surplus loss is proportionally larger in low-income markets; reported as a distributional effect." },
    review: { calcTest: "passed", domainReview: "retail pricing reviewer (synthetic)", economicReview: "industrial organisation economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set RT-07-p1, 2026-09-12" },
    limitations: ["Competitor responses beyond twelve months unobserved", "Legal exposure is assessed, not observed", "Consumer surplus uses a linear approximation"] },

  /* ------------------------------------------------------------------ 8 */
  { id: "LG-08", industry: "Transportation, logistics and mobility", appClass: "Optimisation and control", level: "Workflow",
    title: "AI route and dispatch optimisation for a parcel carrier",
    question: "How many miles and driver hours did AI routing remove across 40 depots compared with the dispatcher baseline, and what is the value after service failures and the licence?",
    intendedUse: "Contract dispute over promised savings; internal renewal decision.",
    unit: "Workflow: depot-level miles per stop and hours per route", unitRationale: "Routes are planned per depot per day.",
    period: "2025-Q2 to 2026-Q1", geography: "United States", status: "Reviewed", synthetic: true,
    calibration: "Mileage savings in the low single digits are within published ranges for routing optimisation; all depot economics synthetic.",
    treatment: { system: "Vehicle routing optimiser with live traffic", version: "release 11", deployed: "2025-04-07", scope: "20 of 40 depots (randomly assigned), remaining 20 in 2026-04", autonomy: "Autonomous plan, dispatcher may override", data: "Stop history, traffic feeds", users: "Dispatchers and drivers", complements: ["Driver app update", "Dispatcher training"] },
    comparator: { rank: 1, label: "Randomly assigned control depots", basis: "Twenty depots randomised to the first wave.", contamination: ["Drivers do not move between depots", "Both waves received the app update"] },
    timeline: [["2025-03-01", "Vendor proposal: 12 percent fewer miles", "claim"], ["2025-04-07", "Wave one live", "deployment"], ["2025-08-01", "Override rate falls below 5 percent", "economic"]],
    technical: { outcome: "Miles per stop", unit: "miles per stop", baseline: 1.42 },
    identification: { method: "rct", grade: "A", data: { treated: { units: units(808, 20, 1.335, 0.05) }, control: { units: units(809, 20, 1.421, 0.05) } },
      assumptions: ["Randomisation achieved balance (checked on depot size and density)", "No spillover between depots", "Service failure measured identically"],
      threats: ["Dispatcher overrides dilute the treatment (intent-to-treat effect reported)", "Novelty: drivers followed routes more closely in month one", "Twelve-month horizon; fuel prices changed (common to both arms)"],
      preTrends: "Randomised; balance table shows standardised differences under 0.1." },
    evidence: [syn("E-LG-1", "Miles per stop by depot, wave one and control, 12 months", "A", "Synthetic randomised rollout record"), syn("E-LG-2", "Stops per depot per year 1.9m; cost per mile $0.71; driver hours per mile 0.034 at $34 per hour", "D", "Synthetic operations finance"),
               syn("E-LG-3", "Licence $1.8m per year for 40 depots; integration $1.1m", "D", "Synthetic contract"), syn("E-LG-4", "Late-delivery rate rose 0.3 points in treated depots; credit per late parcel $4.20", "C", "Synthetic service audit"),
               syn("E-LG-5", "Vendor proposal: 12 percent fewer miles", "E", "Vendor proposal")],
    variables: [
      { id: "depots", name: "Depots", value: 40, unit: "depots", evidence: ["E-LG-1"], inference: "Full rollout" },
      { id: "stops", name: "Stops per depot per year", value: 1900000, unit: "stops", evidence: ["E-LG-2"], inference: "Operations finance", low: 1700000, high: 2100000 },
      { id: "costPerMile", name: "Vehicle cost per mile", value: 0.71, unit: "$", evidence: ["E-LG-2"], inference: "Fuel, maintenance, depreciation", low: 0.6, high: 0.85 },
      { id: "hoursPerMile", name: "Driver hours per mile", value: 0.034, unit: "hours", evidence: ["E-LG-2"], inference: "Operations finance" },
      { id: "driverRate", name: "Driver cost per hour", value: 34, unit: "$", evidence: ["E-LG-2"], inference: "Loaded" },
      { id: "hoursRealised", name: "Share of driver hours saved that becomes cash", value: 0.7, unit: "share", evidence: ["E-LG-2"], inference: "Routes consolidated; residual idle time", low: 0.4, high: 0.9, adverse: "low" },
      { id: "licence", name: "Licence per year", value: 1800000, unit: "$", evidence: ["E-LG-3"], inference: "Contract" },
      { id: "integration", name: "Integration (one-off)", value: 1100000, unit: "$", evidence: ["E-LG-3"], inference: "Contract" },
      { id: "lateDelta", name: "Extra late-delivery rate", value: 0.003, unit: "share", evidence: ["E-LG-4"], inference: "Service audit", low: 0, high: 0.006, adverse: "high" },
      { id: "lateCredit", name: "Credit per late parcel", value: 4.2, unit: "$", evidence: ["E-LG-4"], inference: "Service audit" },
      { id: "claimedCut", name: "Claimed mileage reduction", value: 0.12, unit: "share", evidence: ["E-LG-5"], inference: "Grade E" },
      { id: "baseProfitYear", name: "Network contribution without AI", value: 72000000, unit: "$", evidence: ["E-LG-2"], inference: "Synthetic" }
    ],
    model: { horizonYears: 3, discountRate: 0.09, headStartYears: 3, rampYears: 1,
      channels: { variableCost: "effect * depots * stops * (costPerMile + hoursPerMile * driverRate * hoursRealised)", fixedCost: "licence", capital: "integration", expectedLoss: "lateDelta * depots * stops * lateCredit", baseProfit: "baseProfitYear" },
      note: "effect is the change in miles per stop (negative is a saving). Vehicle cost per mile is realised in full; driver hours only to the realised share.",
      claimedValue: "claimedCut * 1.42 * depots * stops * (costPerMile + hoursPerMile * driverRate) * 3", contributionDenominator: "baseProfitYear * 3",
      welfare: [{ label: "Public: fewer vehicle miles per year", formula: "-effect * depots * stops", who: "public", note: "Emissions and congestion benefit, not a cash flow" }, { label: "Customers: additional late parcels per year", formula: "lateDelta * depots * stops", who: "customers", note: "Nonprice harm" }] },
    alternatives: [{ id: "compliers", label: "Depots with override rate under 5 percent only", rank: 4, method: "rct", data: { treated: { units: units(810, 12, 1.318, 0.045) }, control: { units: units(809, 20, 1.421, 0.05) } }, note: "Per-protocol effect; larger, but selected on behaviour" }],
    assumptionWorlds: [{ label: "Driver hours not realised (hoursRealised = 0)", overrides: { hoursRealised: 0 }, note: "Vehicle savings only" }],
    distribution: { subgroups: [{ label: "Urban depots", effect: -0.121 }, { label: "Suburban depots", effect: -0.084 }, { label: "Rural depots", effect: -0.018 }], note: "Rural depots gain little; long fixed legs dominate." },
    review: { calcTest: "passed", domainReview: "logistics operations reviewer (synthetic)", economicReview: "transport economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set LG-08-p1, 2026-09-12" },
    limitations: ["Intent-to-treat effect; per-protocol shown as an alternative", "Fuel-price changes affect the cash value of miles", "Service-failure cost limited to credits"] },

  /* ------------------------------------------------------------------ 9 */
  { id: "EN-09", industry: "Energy, utilities and resources", appClass: "Prediction and classification", level: "Business unit",
    title: "AI load forecasting for a utility's day-ahead purchasing",
    question: "What did a machine-learning load forecast save in imbalance and reserve cost compared with the utility's engineering forecast, where no field counterfactual exists and the answer must be bounded?",
    intendedUse: "Rate-case justification of software spend; vendor renewal.",
    unit: "Business unit: day-ahead purchasing desk", unitRationale: "Only one desk exists; the comparator is the retained engineering forecast run in parallel.",
    period: "2025-Q3 to 2026-Q2", geography: "United States", status: "Reviewed", synthetic: true,
    calibration: "Forecast error reductions of roughly a fifth are within published ranges for ML load forecasting; cost figures synthetic.",
    treatment: { system: "Gradient-boosted load forecast with weather ensembles", version: "forecast 2.4", deployed: "2025-07-01", scope: "Whole service territory", autonomy: "Advisory to traders", data: "Meter data, weather, calendar", users: "Trading desk", complements: ["Weather data subscription"] },
    comparator: { rank: 6, label: "Engineering forecast run in parallel (shadow), translated through the imbalance cost model", basis: "The retained forecast produces a daily shadow position; the cost difference is computed, not observed.", contamination: ["Traders saw both forecasts: behavioural response is the treatment", "Shadow position assumes the desk would have traded the engineering forecast mechanically"] },
    timeline: [["2025-07-01", "Forecast live; engineering forecast retained in shadow", "deployment"], ["2026-01-10", "Winter event: both forecasts miss, AI misses less", "economic"]],
    technical: { outcome: "Annual imbalance and reserve cost avoided", unit: "$ per year", baseline: 0 },
    identification: { method: "bound", grade: "D", data: { low: 2100000, high: 4600000, basis: "Daily shadow-position cost differences summed over the year, with the trader behavioural response bounded between zero and full mechanical use", calibration: "Forecast MAPE 3.1 percent (AI) versus 3.9 percent (engineering) on 365 days" },
      assumptions: ["Imbalance prices in the year are representative", "Traders would have used the engineering forecast mechanically at the upper bound and ignored it at the lower bound", "No feedback from the utility's own position onto imbalance prices"],
      threats: ["No field counterfactual: this is a bound, not a causal estimate", "One extreme winter event drives 30 percent of the difference", "Weather subscription is a complement"],
      preTrends: "Not applicable." },
    evidence: [syn("E-EN-1", "365 days of shadow-position cost differences", "D", "Synthetic desk log"), syn("E-EN-2", "Forecast MAPE by day, both forecasts", "C", "Synthetic forecast verification"),
               syn("E-EN-3", "Software and data subscription $0.9m per year; build $0.5m", "D", "Synthetic budget"), syn("E-EN-4", "Reliance risk: a forecast outage during a peak could cost $3m; assessed probability 3 percent per year", "C", "Synthetic operational risk memo")],
    variables: [
      { id: "software", name: "Software and data per year", value: 900000, unit: "$", evidence: ["E-EN-3"], inference: "Budget" },
      { id: "build", name: "Build (one-off)", value: 500000, unit: "$", evidence: ["E-EN-3"], inference: "Budget" },
      { id: "outageProb", name: "Annual probability of a forecast outage at peak", value: 0.03, unit: "share", evidence: ["E-EN-4"], inference: "Risk memo", low: 0.01, high: 0.08, adverse: "high" },
      { id: "outageCost", name: "Cost of an outage at peak", value: 3000000, unit: "$", evidence: ["E-EN-4"], inference: "Risk memo", low: 1500000, high: 6000000, adverse: "high" },
      { id: "eventShare", name: "Share of the saving from the single winter event", value: 0.30, unit: "share", evidence: ["E-EN-1"], inference: "Desk log", low: 0.2, high: 0.45 },
      { id: "baseProfitYear", name: "Desk cost base without AI (negative contribution)", value: -21000000, unit: "$", evidence: ["E-EN-1"], inference: "Synthetic" }
    ],
    model: { horizonYears: 3, discountRate: 0.07, headStartYears: 3, rampYears: 1,
      channels: { variableCost: "-effect", fixedCost: "software", capital: "build", expectedLoss: "outageProb * outageCost", baseProfit: "baseProfitYear" },
      note: "effect is the bounded annual cost avoided in dollars; the case reports a range, not a point, because the identification is an engineering bound (grade D).",
      welfare: [{ label: "Ratepayers: share of avoided cost passed through", formula: "effect * 0.9", who: "ratepayers", note: "Regulated pass-through; the utility retains little of the saving" }] },
    alternatives: [{ id: "noevent", label: "Excluding the winter event", rank: 6, method: "bound", data: { low: 1470000, high: 3220000, basis: "Shadow differences excluding 10 to 14 January", calibration: "Same verification" }, note: "A normal year" },
                   { id: "mech", label: "Full mechanical use of the engineering forecast", rank: 6, method: "bound", data: { low: 4600000, high: 4600000, basis: "Upper bound only", calibration: "Same verification" }, note: "The most favourable behavioural assumption" }],
    assumptionWorlds: [{ label: "Outage probability at the top of its range", overrides: { outageProb: 0.08 }, note: "Reliance risk" }],
    distribution: { subgroups: [{ label: "Summer peak days", effect: 1300000 }, { label: "Winter peak days", effect: 1900000 }, { label: "Shoulder months", effect: 150000 }], note: "The saving is concentrated on peak days." },
    review: { calcTest: "passed", domainReview: "power trading reviewer (synthetic)", economicReview: "regulatory economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set EN-09-p1, 2026-09-12" },
    limitations: ["Bound, not a causal estimate", "One year of weather", "Trader behaviour unobserved"] },

  /* ------------------------------------------------------------------ 10 */
  { id: "MD-10", industry: "Media, advertising and content", appClass: "Generation and synthesis", level: "Product feature",
    title: "Generative AI creative in a consumer advertising programme",
    question: "Did AI-generated creative lower production cost and change conversion in a randomised campaign test, and does the programme gain once brand and rights exposure are priced?",
    intendedUse: "Consumer-claims and IP exposure assessment; agency contract renewal.",
    unit: "Product feature: creative variant within campaigns", unitRationale: "Campaigns were randomised by creative source at the placement level.",
    period: "2025-Q4 to 2026-Q2", geography: "United States and Europe", status: "Reviewed", synthetic: true,
    calibration: "Production cost reductions are large and well documented; conversion effects near zero are consistent with published creative tests. Rights exposure is synthetic.",
    treatment: { system: "Image and copy generation with brand style controls", version: "model family refreshed 2026-02", deployed: "2025-10-15", scope: "Half of placements in 14 campaigns", autonomy: "Human-reviewed before publication", data: "Brand assets and prior creative", users: "Creative team", complements: ["Faster testing cadence"] },
    comparator: { rank: 1, label: "Randomised placements with agency-produced creative", basis: "Placements randomised within each campaign.", contamination: ["Same media plan and budget in both arms", "Reviewers blind to source at approval stage (checked)"] },
    timeline: [["2025-10-15", "Test begins", "deployment"], ["2026-02-01", "Model refresh", "version"], ["2026-03-12", "Rights claim received on one generated image", "risk"]],
    technical: { outcome: "Conversion rate per impression", unit: "share", baseline: 0.0182 },
    identification: { method: "rct", grade: "A", data: { treated: { units: units(1010, 60, 0.01795, 0.0011) }, control: { units: units(1011, 60, 0.0182, 0.0011) } },
      assumptions: ["Randomisation at placement level", "No spillover between arms within a campaign", "Conversion attribution identical"],
      threats: ["Brand effect is long-run and not measured in conversion", "Rights exposure is a tail risk unrepresented in twelve months", "Reviewer approval may filter the weakest AI creative (part of the treatment as deployed)"],
      preTrends: "Randomised; balance on campaign, placement type and budget." },
    evidence: [syn("E-MD-1", "120 placements with impressions, conversions and creative source", "A", "Synthetic randomised campaign log"), syn("E-MD-2", "Production cost per creative $6,800 agency versus $900 generated plus review", "D", "Synthetic agency invoices"),
               syn("E-MD-3", "Impressions per year 420m; margin per conversion $38", "D", "Synthetic marketing finance"), syn("E-MD-4", "Rights claim on one image: settlement and legal $180,000; counsel estimates 15 percent annual probability of a further claim at $600,000", "C", "Synthetic legal memo"),
               syn("E-MD-5", "Brand tracker: no change in aided awareness at 6 months (within 1 point)", "C", "Synthetic brand tracker"), syn("E-MD-6", "Tooling $240,000 per year", "D", "Synthetic budget")],
    variables: [
      { id: "creatives", name: "Creatives produced per year", value: 640, unit: "creatives", evidence: ["E-MD-2"], inference: "Creative calendar", low: 500, high: 800 },
      { id: "costAgency", name: "Cost per agency creative", value: 6800, unit: "$", evidence: ["E-MD-2"], inference: "Invoices" },
      { id: "costGen", name: "Cost per generated creative including review", value: 900, unit: "$", evidence: ["E-MD-2"], inference: "Invoices and time", low: 600, high: 1500, adverse: "high" },
      { id: "impressions", name: "Impressions per year", value: 420000000, unit: "impressions", evidence: ["E-MD-3"], inference: "Marketing finance" },
      { id: "marginPerConv", name: "Margin per conversion", value: 38, unit: "$", evidence: ["E-MD-3"], inference: "Marketing finance", low: 30, high: 46 },
      { id: "tooling", name: "Tooling per year", value: 240000, unit: "$", evidence: ["E-MD-6"], inference: "Budget" },
      { id: "claimPaid", name: "Rights claim paid (one-off)", value: 180000, unit: "$", evidence: ["E-MD-4"], inference: "Legal memo" },
      { id: "claimProb", name: "Annual probability of a further rights claim", value: 0.15, unit: "share", evidence: ["E-MD-4"], inference: "Legal memo", low: 0.05, high: 0.35, adverse: "high" },
      { id: "claimCost", name: "Cost of a further claim", value: 600000, unit: "$", evidence: ["E-MD-4"], inference: "Legal memo", low: 200000, high: 1500000, adverse: "high" },
      { id: "baseProfitYear", name: "Programme contribution without AI", value: 18000000, unit: "$", evidence: ["E-MD-3"], inference: "Synthetic" }
    ],
    model: { horizonYears: 3, discountRate: 0.10, headStartYears: 1, rampYears: 1,
      channels: { revenue: "effect * impressions * marginPerConv", variableCost: "-(creatives * (costAgency - costGen))", fixedCost: "tooling", capital: "claimPaid", expectedLoss: "claimProb * claimCost", baseProfit: "baseProfitYear" },
      note: "effect is the change in conversion rate: small, negative and not statistically distinguishable from zero, yet on 420 million impressions it is worth as much as the production saving. The head start is one year because agencies now offer the same tooling at lower prices.",
      contributionDenominator: "baseProfitYear * 3",
      welfare: [{ label: "Creative workers: agency hours displaced per year", formula: "creatives * 42", who: "workers", note: "Labour displacement, reported and not netted" }, { label: "Rights holders: exposure events per year", formula: "claimProb", who: "rights holders", note: "Probability of a claim" }] },
    alternatives: [{ id: "post", label: "Post-refresh placements only", rank: 1, method: "rct", data: { treated: { units: units(1012, 30, 0.0184, 0.0011) }, control: { units: units(1011, 60, 0.0182, 0.0011) } }, note: "Newer model, smaller sample" }],
    assumptionWorlds: [{ label: "Head start three years (agencies do not adopt)", overrides: { headStartYears: 3 }, note: "The saving persists" }, { label: "Brand effect of minus 1 percent conversion in year two (unmeasured)", overrides: { effect: -0.00018 }, note: "A brand tracker cannot see this within the window" }],
    distribution: { subgroups: [{ label: "Performance placements", effect: 0.0002 }, { label: "Brand placements", effect: -0.0009 }], note: "Brand placements convert worse with generated creative; the average hides it." },
    review: { calcTest: "passed", domainReview: "marketing measurement reviewer (synthetic)", economicReview: "IP economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set MD-10-p1, 2026-09-12" },
    limitations: ["Brand effects beyond six months unmeasured", "Rights exposure assessed, not observed", "One-year head start is a market judgement"] },

  /* ------------------------------------------------------------------ 11 */
  { id: "SW-11", industry: "Software, cloud and digital platforms", appClass: "Generation and synthesis", level: "Task",
    title: "AI coding assistant across an engineering organisation",
    question: "Did an AI coding assistant change cycle time and defect rates for 240 developers in a randomised rollout, and what is the value after incident risk and licences?",
    intendedUse: "Internal investment decision; securities-disclosure check on productivity claims.",
    unit: "Task: pull request cycle time and defects per thousand lines", unitRationale: "Developers were randomised; outcomes are per developer.",
    period: "2025-Q3 to 2026-Q2", geography: "Global", status: "Reviewed", synthetic: true,
    calibration: "Cycle-time gains in the 10 to 25 percent range and mixed defect results are consistent with published developer experiments. Organisation economics synthetic.",
    treatment: { system: "In-editor code completion and chat", version: "assistant 4.x", deployed: "2025-07-15", scope: "120 of 240 developers randomised", autonomy: "Advisory; code review unchanged", data: "Public models, no fine-tuning", users: "Developers", complements: ["No change to review policy (checked)"] },
    comparator: { rank: 1, label: "Randomised developers without the assistant", basis: "Randomised by individual within teams.", contamination: ["Spillover within teams possible: reviewers see AI-written code (would understate effect)", "Licence honoured only for assigned developers (checked)"] },
    timeline: [["2025-07-15", "Rollout to treated developers", "deployment"], ["2025-11-03", "Incident traced to an AI-suggested dependency", "risk"], ["2026-01-20", "Assistant 4.2", "version"]],
    technical: { outcome: "Pull requests merged per developer per month", unit: "PRs per month", baseline: 9.4 },
    identification: { method: "rct", grade: "A", data: { treated: { units: units(1111, 120, 10.9, 2.6) }, control: { units: units(1112, 120, 9.4, 2.5) } },
      assumptions: ["Randomisation balanced on tenure and language (checked)", "PR size unchanged (median lines within 4 percent)", "Defects measured by the same post-merge rule"],
      threats: ["Within-team spillover understates the effect", "Developers may split work into more PRs (size checked)", "Incident risk is a tail event with one observation"],
      preTrends: "Randomised; balance on tenure, language, team." },
    evidence: [pub(PUB.jagged, "Abstract"), syn("E-SW-1", "Monthly PRs merged per developer, both arms, 10 months", "A", "Synthetic repository analytics, randomised"), syn("E-SW-2", "Loaded developer cost $185,000 per year; 1,700 productive hours", "D", "Synthetic HR summary"),
               syn("E-SW-3", "Licence $39 per developer per month", "D", "Synthetic contract"), syn("E-SW-4", "Post-merge defects per thousand lines 1.31 (assistant) versus 1.22 (control); rework $410 per defect", "B", "Synthetic defect tracker"),
               syn("E-SW-5", "Incident from an AI-suggested vulnerable dependency: $260,000 remediation; security team estimates 20 percent annual probability of recurrence at $500,000", "C", "Synthetic incident report"), syn("E-SW-6", "Output realised as delivered features: product leadership estimates 50 percent, remainder absorbed by review and backlog", "E", "Management estimate")],
    variables: [
      { id: "developers", name: "Developers", value: 240, unit: "people", evidence: ["E-SW-1"], inference: "Full rollout" },
      { id: "devCost", name: "Loaded cost per developer per year", value: 185000, unit: "$", evidence: ["E-SW-2"], inference: "HR summary", low: 160000, high: 210000 },
      { id: "realised", name: "Share of extra output that has cash value", value: 0.5, unit: "share", evidence: ["E-SW-6"], inference: "Management estimate, grade E", low: 0.2, high: 0.8, adverse: "low" },
      { id: "licence", name: "Licence per developer per year", value: 468, unit: "$", evidence: ["E-SW-3"], inference: "$39 × 12" },
      { id: "linesPerDev", name: "Thousand lines merged per developer per year", value: 48, unit: "kLOC", evidence: ["E-SW-4"], inference: "Defect tracker" },
      { id: "defectDelta", name: "Extra defects per thousand lines", value: 0.09, unit: "per kLOC", evidence: ["E-SW-4"], inference: "1.31 minus 1.22", low: 0.0, high: 0.2, adverse: "high" },
      { id: "reworkCost", name: "Rework per defect", value: 410, unit: "$", evidence: ["E-SW-4"], inference: "Defect tracker" },
      { id: "incidentPaid", name: "Incident remediation (one-off)", value: 260000, unit: "$", evidence: ["E-SW-5"], inference: "Incident report" },
      { id: "incidentProb", name: "Annual probability of recurrence", value: 0.2, unit: "share", evidence: ["E-SW-5"], inference: "Security estimate", low: 0.05, high: 0.4, adverse: "high" },
      { id: "incidentCost", name: "Cost per incident", value: 500000, unit: "$", evidence: ["E-SW-5"], inference: "Security estimate", low: 200000, high: 2000000, adverse: "high" },
      { id: "baseProfitYear", name: "Engineering output value without AI", value: 44400000, unit: "$", evidence: ["E-SW-2"], inference: "Synthetic: developers × cost" }
    ],
    model: { horizonYears: 3, discountRate: 0.10, headStartYears: 3, rampYears: 1,
      channels: { revenue: "(effect / 9.4) * developers * devCost * realised", fixedCost: "developers * licence + defectDelta * linesPerDev * developers * reworkCost", capital: "incidentPaid", expectedLoss: "incidentProb * incidentCost", baseProfit: "baseProfitYear" },
      note: "effect is extra PRs per developer per month; output is valued at cost, times the realised share. Extra rework is a recurring cost; the incident is a one-off plus an expected loss.",
      contributionDenominator: "baseProfitYear * 3",
      welfare: [{ label: "Developers: share reporting higher job satisfaction", formula: "0.31", who: "workers", note: "Survey, nonprice" }] },
    alternatives: [{ id: "junior", label: "Developers with under two years' tenure", rank: 1, method: "rct", data: { treated: { units: units(1113, 40, 12.1, 2.7) }, control: { units: units(1114, 40, 9.1, 2.5) } }, note: "Largest gains; not the population effect" }],
    assumptionWorlds: [{ label: "Realised share at the management estimate's top (0.8)", overrides: { realised: 0.8 }, note: "Grade E input driving the result" }, { label: "Assistant 4.2 only (last five months)", overrides: { effect: 1.8, defectDelta: 0.05 }, note: "Newer version" }],
    distribution: { subgroups: [{ label: "Junior developers", effect: 3.0 }, { label: "Senior developers", effect: 0.4 }, { label: "Security-sensitive repositories", effect: -0.3 }], note: "Security-sensitive repositories saw slower merges with the assistant because review tightened." },
    review: { calcTest: "passed", domainReview: "engineering productivity reviewer (synthetic)", economicReview: "labour economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set SW-11-p1, 2026-09-12" },
    limitations: ["The realised-output share is a grade E management estimate and controls the result", "Ten months of data", "Incident risk from one observation"] },

  /* ------------------------------------------------------------------ 12 */
  { id: "PS-12", industry: "Public services and education", appClass: "Prediction and classification", level: "Workflow",
    title: "AI case triage in a benefits administration office network",
    question: "Did AI triage cut processing time and cost across a staged rollout of offices, and who bore the errors?",
    intendedUse: "Regulatory and public-policy assessment; procurement review.",
    unit: "Workflow: days to decision per case", unitRationale: "Cases are processed per office; rollout was staged by region.",
    period: "2025-Q2 to 2026-Q2", geography: "One national administration", status: "Reviewed", synthetic: true,
    calibration: "Processing-time reductions and error patterns are synthetic; distributional concerns follow published audits of automated benefits systems.",
    treatment: { system: "Triage model routing cases to fast-track, standard or review queues", version: "triage 1.3", deployed: "2025-05-01", scope: "Staged over three regions", autonomy: "Autonomous routing; decisions remain human", data: "Historical case records", users: "Caseworkers", complements: ["Queue redesign", "Staff reallocation between regions"] },
    comparator: { rank: 2, label: "Staged office rollout: regions awaiting deployment", basis: "Regions scheduled by IT readiness.", contamination: ["Staff reallocation moved 6 percent of caseworkers toward treated regions (a complement, cost included)", "Case mix differs by region: reweighted on case type"] },
    timeline: [["2025-05-01", "Region one live", "deployment"], ["2025-09-01", "Region two live", "deployment"], ["2026-01-15", "Audit finds higher wrongful-denial rate in fast-track for one applicant group", "risk"], ["2026-02-01", "Region three live", "deployment"]],
    technical: { outcome: "Days to decision", unit: "days", baseline: 31 },
    identification: { method: "did", grade: "B", data: { treated: { pre: [31.2, 30.8, 31.1, 31.4, 30.9, 31.0], post: [26.1, 24.4, 23.6, 23.2, 23.0, 22.9] }, control: { pre: [31.0, 30.9, 31.2, 31.1, 31.0, 31.3], post: [30.8, 30.6, 30.9, 30.7, 30.5, 30.6] } },
      assumptions: ["Parallel trends across regions", "Case mix reweighting removes composition effects", "Staff reallocation is part of the treatment package"],
      threats: ["Wrongful denials shift cost to applicants and to the appeals system (welfare, not netted)", "Staff reallocation confounds (included as a complement cost)", "Reweighting depends on case-type coding"],
      preTrends: "Pre-period slopes minus 0.01 (treated) and plus 0.05 (control) days per month; the gap of 0.06 days per month is small against an effect of about 7 days." },
    evidence: [syn("E-PS-1", "Monthly days to decision by region, reweighted", "D", "Synthetic case-management export"), syn("E-PS-2", "Cases per year 1.4m; administrative cost per case-day $3.10", "D", "Synthetic budget"),
               syn("E-PS-3", "Wrongful-denial rate in fast-track 2.9 percent versus 2.1 percent standard; appeal and re-adjudication cost $340 per case; average benefit delayed $1,900", "B", "Synthetic audit"),
               syn("E-PS-4", "System $3.4m per year; build $5.2m; staff reallocation cost $1.1m", "D", "Synthetic procurement file"), syn("E-PS-5", "Ministerial statement: decisions 40 percent faster", "E", "Public statement")],
    variables: [
      { id: "cases", name: "Cases per year", value: 1400000, unit: "cases", evidence: ["E-PS-2"], inference: "Budget" },
      { id: "costPerDay", name: "Administrative cost per case-day", value: 3.1, unit: "$", evidence: ["E-PS-2"], inference: "Budget", low: 2.4, high: 3.8 },
      { id: "realised", name: "Share of processing-time saving realised as cost", value: 0.45, unit: "share", evidence: ["E-PS-4"], inference: "Staffing plan", low: 0.2, high: 0.7, adverse: "low" },
      { id: "fastShare", name: "Share of cases fast-tracked", value: 0.38, unit: "share", evidence: ["E-PS-3"], inference: "Audit" },
      { id: "denialDelta", name: "Extra wrongful-denial rate in fast-track", value: 0.008, unit: "share", evidence: ["E-PS-3"], inference: "2.9 minus 2.1 percent", low: 0.003, high: 0.015, adverse: "high" },
      { id: "appealCost", name: "Appeal and re-adjudication cost per case", value: 340, unit: "$", evidence: ["E-PS-3"], inference: "Audit" },
      { id: "benefitDelayed", name: "Average benefit delayed per wrongful denial", value: 1900, unit: "$", evidence: ["E-PS-3"], inference: "Audit" },
      { id: "system", name: "System per year", value: 3400000, unit: "$", evidence: ["E-PS-4"], inference: "Procurement" },
      { id: "build", name: "Build and reallocation (one-off)", value: 6300000, unit: "$", evidence: ["E-PS-4"], inference: "Procurement" },
      { id: "claimedCut", name: "Claimed speed-up", value: 0.40, unit: "share", evidence: ["E-PS-5"], inference: "Grade E" },
      { id: "baseProfitYear", name: "Administration cost base without AI (negative)", value: -135000000, unit: "$", evidence: ["E-PS-2"], inference: "Synthetic" }
    ],
    model: { horizonYears: 4, discountRate: 0.05, headStartYears: 4, rampYears: 1,
      channels: { variableCost: "effect * cases * costPerDay * realised", fixedCost: "system", capital: "build", expectedLoss: "denialDelta * fastShare * cases * appealCost", baseProfit: "baseProfitYear" },
      note: "effect is the change in days to decision (negative is faster). The administration's expected loss counts only appeal costs; the benefit delayed to applicants is a welfare item and is larger.",
      claimedValue: "claimedCut * 31 * cases * costPerDay * realised * 4",
      welfare: [{ label: "Applicants: benefits delayed by wrongful denial per year", formula: "-(denialDelta * fastShare * cases * benefitDelayed)", who: "applicants", note: "Borne by applicants, larger than the administration's expected loss" },
                { label: "Applicants: faster decisions (days)", formula: "-effect", who: "applicants", note: "Nonprice benefit for those correctly processed" }] },
    alternatives: [{ id: "region1", label: "Region one only (longest exposure)", rank: 2, method: "did", data: { treated: { pre: [31.0, 30.9, 31.2, 31.1, 30.8, 31.0], post: [25.0, 23.4, 22.9, 22.6, 22.4, 22.3] }, control: { pre: [31.0, 30.9, 31.2, 31.1, 31.0, 31.3], post: [30.8, 30.6, 30.9, 30.7, 30.5, 30.6] } }, note: "Best case region" }],
    assumptionWorlds: [{ label: "Fast-track threshold tightened after the audit", overrides: { effect: -5.6, denialDelta: 0.003, fastShare: 0.29 }, note: "Fewer fast-tracked cases, fewer wrongful denials, smaller speed-up" }],
    distribution: { subgroups: [{ label: "Standard applicants", effect: -9.1 }, { label: "Applicants with incomplete records", effect: -3.2 }, { label: "One applicant group (audit finding)", effect: -6.0 }], note: "Speed-ups differ; the wrongful-denial burden falls on one group, reported in welfare." },
    review: { calcTest: "passed", domainReview: "benefits administration reviewer (synthetic)", economicReview: "public economist (synthetic)", version: "1.0", extraction: "Extraction logged: nova-lite-v1, prompt set PS-12-p1, 2026-09-12" },
    limitations: ["Twelve months; appeals lag", "Reweighting depends on case-type coding", "Applicant harm is only partly priced"] }
  ];

  global.AICF_CASES = CASES;
  global.AICF_SOURCES = PUB;
})(typeof window !== "undefined" ? window : globalThis);
